=== Brtsz8/HobbyWebsite/myHobby.dtd
<!ELEMENT myHobby (combatSports, organizations, fighters, popular)>

<!ELEMENT combatSports (sport+)>
<!ELEMENT sport (#PCDATA)>
<!ATTLIST sport
    abbreviation CDATA #IMPLIED>

<!ELEMENT organizations (organization+)>
<!ELEMENT organization (name, disciplines?, founded?, link?)>
<!ATTLIST organization
    president CDATA #IMPLIED>
<!ATTLIST organization
    abbreviation CDATA #IMPLIED>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
    abbreviation CDATA #IMPLIED>
<!ELEMENT disciplines (discipline+)>
<!ELEMENT discipline (#PCDATA)>
<!ATTLIST discipline
    abbreviation CDATA #IMPLIED
    style CDATA #IMPLIED>
<!ELEMENT founded (#PCDATA)>
<!ELEMENT link EMPTY>
<!ATTLIST link
    source CDATA #REQUIRED>

<!ELEMENT fighters (fighter+)>
<!ELEMENT fighter (firstName, lastName, age, from, competedIn, image)>
<!ELEMENT firstName (#PCDATA)>
<!ATTLIST firstName
    nickname CDATA #IMPLIED>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ATTLIST from
    represents (Yes | No | Used_to) #REQUIRED>
<!ELEMENT competedIn (organizations, disciplines)>
<!ATTLIST competedIn
    retired (yes | no) #REQUIRED>
<!ELEMENT image (img)>
<!ELEMENT img EMPTY>
<!ATTLIST img
    source CDATA #REQUIRED
    alt CDATA #IMPLIED
    width CDATA #IMPLIED
    height CDATA #IMPLIED>

<!ELEMENT popular (popularFighter+, popularGyms+)>
<!ELEMENT popularFighter (#PCDATA)>
<!ELEMENT popularGyms (#PCDATA)>

<!ENTITY % organizationElements "name, disciplines, founded, link?">
<!ENTITY % linkAttributes "source CDATA #REQUIRED">

=== Brtsz8/HobbyWebsite/data_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE myHobby SYSTEM "myHobby.dtd">
<myHobby>
    <combatSports>
        <sport>Boxing</sport>
        <sport abbreviation="MMA">Mixed Martial Arts</sport>
        <sport abbreviation="BJJ">Brazilian Jiu Jitsu</sport>
        <sport>Muay Thai</sport>
        <sport>Wrestling</sport>
        <sport>Kickboxing</sport>
        <sport>Judo</sport>
        <sport>Karate</sport>
    </combatSports>
    <organizations>
        <organization president="Dana White">
            <name abbreviation="UFC">Ultimate Fighting Championship</name>
            <disciplines>
                <discipline abbreviation="MMA">Mixed Martial Arts</discipline>
            </disciplines> 
            <founded>1993</founded>
            <link source="https://www.ufc.com/"/>   
        </organization>
        <organization>
            <name abbreviation="WBA">World Boxing Association</name>
            <disciplines>
                <discipline>Boxing</discipline>
            </disciplines> 
            <founded>1962</founded>
            <link source="https://www.wbaboxing.com/"/>   
        </organization>
        <organization>
            <name>ONE Championship</name>
            <disciplines>
                <discipline abbreviation="MMA">Mixed Martial Arts</discipline>
                <discipline>Kickboxing</discipline>
                <discipline>Muay Thai</discipline>
            </disciplines> 
            <founded>2011</founded>   
            <link source="https://www.onefc.com/"/>
        </organization>
        <organization>
            <name>Karate Combat</name>
            <disciplines>
                <discipline style="modern">Karate</discipline>
            </disciplines> 
            <founded>2011</founded>   
        </organization>
    </organizations>   
    <fighters>
        <fighter>
            <firstName nickname="Poatan">Alex</firstName>
            <lastName>Pereira</lastName>
            <age>37</age>
            <from represents="Yes">Brazil</from>
            <competedIn retired="no">
                <organizations>
                    <organization><name>Glory</name></organization>
                    <organization abbreviation="UFC"><name>Ultimate Fighting Championship</name></organization>
                </organizations>
                <disciplines>
                    <discipline abbreviation="MMA">Mixed Martial Arts</discipline>
                    <discipline>Kickboxing</discipline>
                </disciplines>
            </competedIn>
            <image>
                <img source="img/AlexP.jpg" alt="AlexPereira" width="300" height="300"/>
            </image>
        </fighter>
        <fighter>
            <firstName nickname="JJ">Joanna</firstName>
            <lastName>Jędrzejczyk</lastName>
            <age>37</age>
            <from represents="Used_to">Poland</from>
            <competedIn retired="yes">
                <organizations>
                    <organization abbreviation="UFC"><name>Ultimate Fighting Championship</name></organization>
                </organizations>
                <disciplines>
                    <discipline abbreviation="MMA">Mixed Martial Arts</discipline>
                    <discipline>Muay Thai</discipline>
                </disciplines>
            </competedIn>
            <image>
                <img source="img/JoannaJ.png" alt="JoannaJędrzejczyk" width="300" height="300"/>
            </image>
        </fighter>
        <fighter>
            <firstName>Craig</firstName>
            <lastName>Jones</lastName>
            <age>33</age>
            <from represents="Yes">Australia</from>
            <competedIn retired="no">
                <organizations>
                    <organization abbreviation="ADCC"><name>Abu Dhabi Combat Club</name></organization>
                </organizations>
                <disciplines>
                    <discipline abbreviation="BJJ">Brazilian jiu-jitsu</discipline>
                </disciplines>
            </competedIn>
            <image>
                <img source="img/CraigJ.jpg" alt="CraigJones" width="300" height="300"/>
            </image>
        </fighter>
    </fighters>
    <popular>
        <popularFighter>Conor McGregor</popularFighter>
        <popularFighter>Khabib Nurmagomedov</popularFighter>
        <popularFighter>Anderson Silva</popularFighter>
        <popularFighter>Jon Jones</popularFighter>
        <popularGyms>American Top Team</popularGyms>
        <popularGyms>http://www.elitefighters.com</popularGyms>
    </popular>
    
</myHobby>
